import { useState, useRef, useMemo, useEffect } from 'react';
import { reachableTargets, allLegalMoves } from '../game/gameLogic.js';
import boards from '../game/boards/index.js';

// ─── Piece images (loaded at build time by Vite) ──────────────────────────────
// The default "paper" set is generated by:  npm run extract-pieces
// Additional sets live under pieces/<set>/<player>/*.png. A set with no art
// resolves to empty arrays → checkers fall back to solid-colour circles.
const _ashtonPaper  = import.meta.glob('../assets/pieces/ashton/*.png',  { eager: true });
const _charliePaper = import.meta.glob('../assets/pieces/charlie/*.png', { eager: true });
// Future sets, e.g. pieces/felt/ashton/*.png — add a glob here when art exists.

const sorted = mods => Object.keys(mods).sort().map(k => mods[k].default);

const PIECE_SETS = {
  paper: { ashton: sorted(_ashtonPaper), charlie: sorted(_charliePaper) },
  // 'felt' has no art yet → empty arrays → colored-circle fallback (proves swap)
  felt:  { ashton: [], charlie: [] },
};

// ─── Calibration mode ────────────────────────────────────────────────────────
// Set to true, run dev server, tap points in order, read console, paste into
// sharpieBoard.js, then set back to false.
const CALIBRATION_MODE = false;

const CALIB_TARGETS = [
  ...Array.from({ length: 24 }, (_, i) => ({
    label: `Point ${i}`,
    fmt: (x, y) => `    ${String(i).padEnd(2)}: { x: ${x}, y: ${y} },`,
  })),
  { label: 'Bar — Ashton',       fmt: (x, y) => `  bar.ashton:   { x: ${x}, y: ${y} },` },
  { label: 'Bar — Charlie',      fmt: (x, y) => `  bar.charlie:  { x: ${x}, y: ${y} },` },
  { label: 'Bear-off — Ashton',  fmt: (x, y) => `  bearOff.ashton:  { x: ${x}, y: ${y} },` },
  { label: 'Bear-off — Charlie', fmt: (x, y) => `  bearOff.charlie: { x: ${x}, y: ${y} },` },
];

// ─── Image lookup ─────────────────────────────────────────────────────────────
// Maps (player, point/bar slot, stack index) → a piece image URL for this game.
// Uses a per-game shuffle stored in gameState.pieceImages so the arrangement
// looks handmade and is stable through the whole game session.
function getImg(player, slotId, stackIdx, pieceImages, pieceSet = 'paper') {
  const set = PIECE_SETS[pieceSet] ?? PIECE_SETS.paper;
  const pieces = set[player];
  if (!pieces?.length || !pieceImages?.[player]) return null;
  // Hash slot + stack to an index in the shuffled array
  const n = ((slotId * 7 + stackIdx * 3) % 15 + 15) % 15;
  return pieces[pieceImages[player][n]] ?? null;
}

// ─── Position helpers — all coordinate math driven by board config ────────────

// First N pieces stack normally; the 6th starts a SECOND LAYER back at the
// base piece (like a real board): 6th sits on the 1st, 7th on the 2nd, etc.
// Each layer is nudged along the stack direction so the piece underneath
// peeks out, and higher stackIndex = higher zIndex, so layers read as piles.
const STACK_NORMAL = 5;
const LAYER_OFFSET = 0.45; // how far (in stack steps) each layer shifts inward

function checkerPos(config, pointIndex, stackIndex) {
  const base     = config.points[pointIndex];
  const isBottom = pointIndex <= 11;
  const dir      = isBottom ? config.stackDirection.bottom : config.stackDirection.top;
  const sign     = dir === 'up' ? -1 : 1;

  const layer  = Math.floor(stackIndex / STACK_NORMAL);
  const within = stackIndex % STACK_NORMAL;
  const dy = sign * (within + layer * LAYER_OFFSET) * config.stackStep;

  return { x: base.x, y: base.y + dy };
}

function barPos(config, player, stackIndex) {
  const base   = config.bar[player];
  const dirKey = player === 'ashton' ? 'barAshton' : 'barCharlie';
  const dir    = config.stackDirection[dirKey];
  const dy     = dir === 'up' ? -stackIndex * config.stackStep : stackIndex * config.stackStep;
  return { x: base.x, y: base.y + dy };
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function BackgammonBoard({ state, onSelectPiece, onMovePath, onBlockedTap, boardId = 'sharpie', pieceSet = 'paper', flashPoint = null, charlieTrail = [], hoverPoint = null }) {
  const config = boards[boardId] ?? boards['sharpie'];
  const boardRef = useRef(null);

  const [calibTarget, setCalibTarget] = useState(0);
  const [cursorPx, setCursorPx] = useState(null);

  // Brief shake on a checker that was tapped but can't move ('bar' or index).
  // Cleared via effect so handlers stay ref-free.
  const [nudgePoint, setNudgePoint] = useState(null);
  useEffect(() => {
    if (nudgePoint === null) return;
    const t = setTimeout(() => setNudgePoint(null), 380);
    return () => clearTimeout(t);
  }, [nudgePoint]);

  // Drag-to-move: { from, x, y, startX, startY, moved } — coords in board %.
  // Pure state: pointerdown is a discrete event, so React has flushed it
  // before pointerup runs — the render closure is always current enough.
  const [drag, setDrag] = useState(null);

  const { points, bar, borneOff, selectedPoint, currentPlayer, phase, pieceImages } = state;

  // Set of point indices (or 'bar') that have at least one legal move available.
  const moveableSources = useMemo(() => {
    if (phase !== 'moving' || currentPlayer !== 'ashton') return new Set();
    return new Set(allLegalMoves(state).map(m => m.from));
  }, [state, phase, currentPlayer]);

  // Map of reachable endpoint → ordered steps, for the selected checker. Includes
  // combined-dice destinations so a single tap can move the full pip count.
  const reachable = useMemo(() => {
    if (selectedPoint === null || phase !== 'moving' || currentPlayer !== 'ashton') return new Map();
    return reachableTargets(state, selectedPoint);
  }, [state, selectedPoint, phase, currentPlayer]);

  // Same map, but for the checker currently being dragged
  const dragFrom = drag?.from ?? null;
  const dragReachable = useMemo(() => {
    if (dragFrom === null || phase !== 'moving' || currentPlayer !== 'ashton') return new Map();
    return reachableTargets(state, dragFrom);
  }, [state, dragFrom, phase, currentPlayer]);

  // Destination dots follow whichever interaction is live: drag beats selection
  const activeReachable = drag?.moved ? dragReachable : reachable;
  const destinations = [...activeReachable.keys()];

  // ── Calibration ───────────────────────────────────────────────────────────
  function handleCalibrationTap(e) {
    const rect = boardRef.current?.getBoundingClientRect();
    if (!rect) return;
    const x = ((e.clientX - rect.left) / rect.width  * 100).toFixed(1);
    const y = ((e.clientY - rect.top)  / rect.height * 100).toFixed(1);
    const target = CALIB_TARGETS[calibTarget];
    if (target) { console.log(target.fmt(x, y)); setCalibTarget(t => t + 1); }
  }

  // Move the selected checker to `dest`, applying the full step sequence at once.
  function moveTo(dest) {
    const steps = reachable.get(dest);
    if (steps) onMovePath(steps);
  }

  // ── Game interactions ─────────────────────────────────────────────────────

  // Tapped one of Ashton's own checkers that has no legal move right now —
  // shake it briefly and let the parent show a hint about why.
  function nudge(point) {
    onBlockedTap?.(point);
    setNudgePoint(point);
  }

  function handlePointTap(i) {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && reachable.has(i)) return moveTo(i);
    if (points[i].player === 'ashton' && selectedPoint !== i && !moveableSources.has(i)) return nudge(i);
    onSelectPiece(i);
  }
  function handleBarTap() {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && reachable.has('off')) return moveTo('off');
    if (bar.ashton > 0 && selectedPoint !== 'bar' && !moveableSources.has('bar')) return nudge('bar');
    onSelectPiece('bar');
  }

  // ── Drag-to-move ──────────────────────────────────────────────────────────
  // Press a checker and slide it to a destination dot; a press without movement
  // falls back to the tap flow above. Pointer capture keeps the events on the
  // checker for the whole gesture.

  function pointerPct(e) {
    // Checkers are absolutely positioned, so their offsetParent is the board
    // container — no ref needed inside render-time handlers.
    const rect = e.currentTarget.offsetParent?.getBoundingClientRect();
    if (!rect || !rect.width || !rect.height) return null;
    return {
      x: ((e.clientX - rect.left) / rect.width) * 100,
      y: ((e.clientY - rect.top) / rect.height) * 100,
    };
  }

  function startDrag(e, from) {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    const p = pointerPct(e);
    if (!p) return;
    try { e.currentTarget.setPointerCapture?.(e.pointerId); } catch { /* tap still works without capture */ }
    setDrag({ from, x: p.x, y: p.y, startX: p.x, startY: p.y, moved: false });
  }

  function moveDrag(e) {
    const p = pointerPct(e);
    if (!p) return;
    setDrag(d => d && {
      ...d, x: p.x, y: p.y,
      moved: d.moved || Math.hypot(p.x - d.startX, p.y - d.startY) > 2.5,
    });
  }

  // Nearest droppable destination: tight on x (points are columns), generous on
  // which half of the board the pointer is in.
  function dropTarget(x, y, reach) {
    let best = null;
    let bestD = Infinity;
    for (const key of reach.keys()) {
      const pos = key === 'off' ? config.bearOff.ashton : config.points[key];
      if (key !== 'off') {
        const isBottom = key <= 11;
        if (isBottom ? y < 38 : y > 62) continue; // wrong half entirely
      }
      const d = Math.abs(x - pos.x);
      if (d < bestD) { bestD = d; best = key; }
    }
    return bestD <= cs * 1.3 ? best : null;
  }

  function endDrag(tapFallback) {
    const d = drag;
    setDrag(null);
    if (!d) return;

    if (!d.moved) return tapFallback();          // it was a tap

    const reach = phase === 'moving' && currentPlayer === 'ashton'
      ? reachableTargets(state, d.from)
      : new Map();
    if (reach.size === 0) return nudge(d.from);  // dragged a stuck checker

    const dest = dropTarget(d.x, d.y, reach);
    const steps = dest != null ? reach.get(dest) : null;
    if (steps) onMovePath(steps);                // otherwise it snaps back
  }

  function cancelDrag() {
    setDrag(null);
  }
  function handleBearOffTap() {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && reachable.has('off')) moveTo('off');
  }

  const cs   = config.checkerSize;
  const done = calibTarget >= CALIB_TARGETS.length;

  return (
    <>
      {CALIBRATION_MODE && (
        <div style={{
          fontFamily: 'monospace', fontSize: 12, color: '#5a3010',
          background: 'rgba(255,240,200,0.95)', border: '1px solid #c8a050',
          borderRadius: 6, padding: '5px 10px', marginBottom: 6,
        }}>
          {done
            ? '✓ Done — paste console output into sharpieBoard.js'
            : <>CALIBRATION — tap <strong>{CALIB_TARGETS[calibTarget].label}</strong> &nbsp;({calibTarget + 1}/{CALIB_TARGETS.length})</>
          }
        </div>
      )}

      <div
        ref={boardRef}
        onPointerDown={CALIBRATION_MODE ? handleCalibrationTap : undefined}
        onPointerMove={CALIBRATION_MODE ? (e) => {
          const r = boardRef.current?.getBoundingClientRect();
          if (r) setCursorPx({ x: e.clientX - r.left, y: e.clientY - r.top });
        } : undefined}
        onPointerLeave={CALIBRATION_MODE ? () => setCursorPx(null) : undefined}
        style={{
          position: 'relative', width: '100%',
          touchAction: 'manipulation', userSelect: 'none',
          WebkitTapHighlightColor: 'transparent',
          cursor: CALIBRATION_MODE ? 'crosshair' : 'default',
        }}
      >
        <img src={config.image} alt="backgammon board" draggable={false}
          style={{ width: '100%', display: 'block', borderRadius: 12 }} />

        {/* Calibration: existing-position markers */}
        {CALIBRATION_MODE && Object.entries(config.points).map(([i, pos]) => (
          <CalibDot key={`cd-${i}`} x={pos.x} y={pos.y} label={i} color="#2080ff" />
        ))}
        {CALIBRATION_MODE && <>
          <CalibDot x={config.bar.ashton.x}  y={config.bar.ashton.y}  label="BA" color="#e05000" />
          <CalibDot x={config.bar.charlie.x} y={config.bar.charlie.y} label="BC" color="#e05000" />
          <CalibDot x={config.bearOff.ashton.x}  y={config.bearOff.ashton.y}  label="OA" color="#008040" />
          <CalibDot x={config.bearOff.charlie.x} y={config.bearOff.charlie.y} label="OC" color="#008040" />
        </>}

        {/* Calibration: cursor label */}
        {CALIBRATION_MODE && cursorPx && !done && (
          <div style={{
            position: 'absolute', left: cursorPx.x + 16, top: cursorPx.y + 4,
            pointerEvents: 'none', zIndex: 50, background: 'rgba(0,0,0,0.75)',
            color: '#fff', fontFamily: 'monospace', fontSize: 11,
            padding: '2px 7px', borderRadius: 4, whiteSpace: 'nowrap',
          }}>
            → {CALIB_TARGETS[calibTarget]?.label}
          </div>
        )}

        {/* Bear-off tap zone */}
        {!CALIBRATION_MODE && destinations.includes('off') && (<>
          <div onPointerDown={(e) => { e.stopPropagation(); handleBearOffTap(); }}
            style={{
              position: 'absolute',
              left: `${config.bearOff.ashton.x - cs}%`, top: `${config.bearOff.ashton.y - cs * 2}%`,
              width: `${cs * 2}%`, height: `${cs * 4}%`, zIndex: 20, cursor: 'pointer',
            }} />
          <DestDot x={config.bearOff.ashton.x} y={config.bearOff.ashton.y} cs={cs} onTap={handleBearOffTap} />
        </>)}

        {/* Bar tap zone — only present when Ashton has a checker on the bar.
            Otherwise this invisible center strip would swallow taps meant for
            checkers/points near the middle of the board. */}
        {!CALIBRATION_MODE && bar.ashton > 0 && (
          <div onPointerDown={(e) => { e.stopPropagation(); handleBarTap(); }}
            style={{
              position: 'absolute',
              left: `${config.bar.ashton.x - 6}%`, top: '5%', width: '12%', height: '90%',
              zIndex: 10, cursor: 'pointer',
            }} />
        )}

        {/* Destination dots */}
        {!CALIBRATION_MODE && destinations.map(dest => {
          if (dest === 'off') return null;
          const pos = checkerPos(config, dest, points[dest].count);
          return <DestDot key={`dest-${dest}`} x={pos.x} y={pos.y} cs={cs} onTap={() => handlePointTap(dest)} />;
        })}

        {/* Circle-underneath markers for pieces that moved this turn.
            charlieTrail persists until Ashton rolls; hoverPoint is the piece the
            currently-hovered die moved (brighter). Rendered below the checkers. */}
        {!CALIBRATION_MODE && charlieTrail.map(pt => {
          if (!points[pt]?.count) return null;
          const pos = checkerPos(config, pt, points[pt].count - 1);
          return <UnderCircle key={`trail-${pt}`} x={pos.x} y={pos.y} cs={cs} variant="trail" />;
        })}
        {!CALIBRATION_MODE && hoverPoint != null && points[hoverPoint]?.count > 0 && (() => {
          const pos = checkerPos(config, hoverPoint, points[hoverPoint].count - 1);
          return <UnderCircle x={pos.x} y={pos.y} cs={cs} variant="hover" />;
        })()}

        {/* Checkers on points */}
        {points.map((pt, i) => {
          if (!pt.count || !pt.player) return null;
          const canMove = moveableSources.has(i) && selectedPoint !== i;
          return Array.from({ length: pt.count }).map((_, si) => {
            const pos = checkerPos(config, i, si);
            const img = getImg(pt.player, i, si, pieceImages, pieceSet);
            const isTop = si === pt.count - 1;
            return (
              <Checker key={`pt-${i}-${si}`} x={pos.x} y={pos.y} cs={cs} player={pt.player} img={img}
                selected={selectedPoint === i && isTop}
                isTopmost={isTop}
                zOrder={si}
                canMove={canMove && isTop}
                isFlashing={flashPoint === i && isTop}
                isNudging={nudgePoint === i && isTop}
                isGhost={drag?.moved && drag.from === i && isTop}
                onDragStart={(e) => startDrag(e, i)}
                onDragMove={moveDrag}
                onDragEnd={() => endDrag(() => handlePointTap(i))}
                onDragCancel={cancelDrag}
                interactive={!CALIBRATION_MODE && phase === 'moving' && currentPlayer === 'ashton' && pt.player === 'ashton'}
              />
            );
          });
        })}

        {/* Count badge — appears only when a point has more than STACK_NORMAL pieces */}
        {!CALIBRATION_MODE && points.map((pt, i) => {
          if (!pt.count || pt.count <= STACK_NORMAL) return null;
          const base     = config.points[i];
          const isBottom = i <= 11;
          const badgeY   = isBottom ? base.y + 4.5 : base.y - 4.5;
          return (
            <div key={`badge-${i}`} style={{
              position: 'absolute',
              left: `${base.x}%`, top: `${badgeY}%`,
              transform: 'translate(-50%, -50%)',
              zIndex: 32, pointerEvents: 'none',
              width: 16, height: 16, borderRadius: '50%',
              background: 'rgba(55,30,8,0.88)',
              color: '#f5e8c0',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 9, fontFamily: 'Georgia, serif', fontWeight: 'bold',
              boxShadow: '0 1px 3px rgba(0,0,0,0.5)',
            }}>
              {pt.count}
            </div>
          );
        })}

        {/* Bar — Ashton */}
        {Array.from({ length: bar.ashton }).map((_, i) => {
          const pos = barPos(config, 'ashton', i);
          const img = getImg('ashton', 24, i, pieceImages, pieceSet);
          const isTop = i === bar.ashton - 1;
          return (
            <Checker key={`bar-a-${i}`} x={pos.x} y={pos.y} cs={cs} player="ashton" img={img}
              selected={selectedPoint === 'bar' && isTop}
              isTopmost={isTop}
              zOrder={i}
              canMove={moveableSources.has('bar') && selectedPoint !== 'bar' && isTop}
              isFlashing={false}
              isNudging={nudgePoint === 'bar' && isTop}
              isGhost={drag?.moved && drag.from === 'bar' && isTop}
              onDragStart={(e) => startDrag(e, 'bar')}
              onDragMove={moveDrag}
              onDragEnd={() => endDrag(handleBarTap)}
              onDragCancel={cancelDrag}
              interactive={!CALIBRATION_MODE && phase === 'moving' && currentPlayer === 'ashton'}
            />
          );
        })}

        {/* Bar — Charlie */}
        {Array.from({ length: bar.charlie }).map((_, i) => {
          const pos = barPos(config, 'charlie', i);
          const img = getImg('charlie', 25, i, pieceImages, pieceSet);
          return (
            <Checker key={`bar-c-${i}`} x={pos.x} y={pos.y} cs={cs} player="charlie" img={img}
              selected={false} isTopmost={false} onTap={() => {}} interactive={false}
            />
          );
        })}

        {/* Borne-off counters */}
        {borneOff.ashton  > 0 && <BorneOffPile count={borneOff.ashton}  x={config.bearOff.ashton.x}  y={config.bearOff.ashton.y}  player="ashton"  cs={cs} />}
        {borneOff.charlie > 0 && <BorneOffPile count={borneOff.charlie} x={config.bearOff.charlie.x} y={config.bearOff.charlie.y} player="charlie" cs={cs} />}

        {/* The checker in flight while dragging */}
        {drag?.moved && (() => {
          const slotId = drag.from === 'bar' ? 24 : drag.from;
          const stackIdx = drag.from === 'bar'
            ? Math.max(0, bar.ashton - 1)
            : Math.max(0, (points[drag.from]?.count ?? 1) - 1);
          const img = getImg('ashton', slotId, stackIdx, pieceImages, pieceSet);
          const lift = '0 8px 20px rgba(0,0,0,0.35), 0 0 0 3px rgba(240,192,64,0.7)';
          return (
            <div style={{
              position: 'absolute', left: `${drag.x}%`, top: `${drag.y}%`,
              width: `${cs}%`, paddingTop: `${cs}%`,
              transform: 'translate(-50%,-50%) scale(1.18)',
              zIndex: 70, pointerEvents: 'none',
            }}>
              {img ? (
                <img src={img} draggable={false} style={{
                  position: 'absolute', inset: 0, width: '100%', height: '100%',
                  borderRadius: '50%', boxShadow: lift,
                }} />
              ) : (
                <div style={{
                  position: 'absolute', inset: 0, borderRadius: '50%',
                  background: '#e8d9b8', border: '2px solid rgba(0,0,0,0.2)', boxShadow: lift,
                }} />
              )}
            </div>
          );
        })()}

        {/* Point tap targets (triangle areas) */}
        {!CALIBRATION_MODE && Array.from({ length: 24 }).map((_, i) => {
          const base     = config.points[i];
          const isBottom = i <= 11;
          return (
            <div key={`tap-${i}`}
              onPointerDown={(e) => { e.stopPropagation(); handlePointTap(i); }}
              style={{
                position: 'absolute',
                left: `${base.x - cs / 2}%`,
                top:  isBottom ? '52%' : `${base.y}%`,
                width: `${cs}%`, height: '42%',
                transform: isBottom ? 'none' : 'translateY(-100%)',
                zIndex: 8, cursor: 'pointer',
              }} />
          );
        })}
      </div>
    </>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function Checker({ x, y, cs, player, img, selected, isTopmost, zOrder = 0, canMove = false, isFlashing = false, isNudging = false, isGhost = false, onDragStart, onDragMove, onDragEnd, onDragCancel, interactive }) {
  // Box shadow: priority — selected > flashing > default
  let innerShadow;
  if (selected) {
    innerShadow = '0 0 0 3px #f0c040, 0 4px 16px rgba(240,192,64,0.6)';
  } else if (isFlashing) {
    innerShadow = '0 0 0 3px rgba(200,120,60,0.85), 0 0 20px rgba(200,120,60,0.55)';
  } else {
    innerShadow = '0 1px 4px rgba(0,0,0,0.25)';
  }

  // Animation priority: nudge (can't move) > flash (happening now) > moveable glow
  const glowAnim = isNudging
    ? 'checkerNudge 0.35s ease-in-out'
    : isFlashing
    ? 'pieceFlash 0.9s ease-out forwards'
    : canMove && !selected
    ? 'moveableGlow 2.4s ease-in-out infinite'
    : 'none';

  const draggable = interactive && isTopmost;
  return (
    <div
      onPointerDown={draggable ? (e) => { e.stopPropagation(); onDragStart?.(e); } : undefined}
      onPointerMove={draggable ? onDragMove : undefined}
      onPointerUp={draggable ? (e) => { e.stopPropagation(); onDragEnd?.(e); } : undefined}
      onPointerCancel={draggable ? onDragCancel : undefined}
      style={{
        position: 'absolute', left: `${x}%`, top: `${y}%`,
        width: `${cs}%`, paddingTop: `${cs}%`,
        transform: `translate(-50%,-50%)${selected ? ' translateY(-6px) scale(1.08)' : ''}`,
        transition: 'transform 0.15s ease',
        // Above the point tap zones (z 8) so a press picks the checker up
        // immediately — no select-first needed before dragging.
        zIndex: selected ? 50 : 12 + zOrder,
        cursor: draggable ? 'grab' : 'default',
        pointerEvents: isTopmost ? 'auto' : 'none',
        // Stop the page scrolling while a checker is being dragged on touch
        touchAction: draggable ? 'none' : undefined,
        opacity: isGhost ? 0.35 : 1,
      }}
    >
      {img ? (
        <img src={img} draggable={false} style={{
          position: 'absolute', inset: 0, width: '100%', height: '100%',
          borderRadius: '50%',
          boxShadow: innerShadow,
          animation: glowAnim,
        }} />
      ) : (
        <div style={{
          position: 'absolute', inset: 0, borderRadius: '50%',
          background: player === 'ashton' ? '#e8d9b8' : '#7a5430',
          border: selected ? '3px solid #f0c040' : '2px solid rgba(0,0,0,0.2)',
          boxShadow: innerShadow,
          animation: glowAnim,
        }} />
      )}
    </div>
  );
}

function DestDot({ x, y, cs, onTap }) {
  const d = cs * 0.8;
  return (
    <div onPointerDown={(e) => { e.stopPropagation(); onTap(); }}
      style={{
        position: 'absolute', left: `${x}%`, top: `${y}%`,
        width: `${d}%`, paddingTop: `${d}%`,
        transform: 'translate(-50%,-50%)', zIndex: 22, cursor: 'pointer',
        borderRadius: '50%', background: 'rgba(240,185,50,0.9)',
        border: '2.5px solid rgba(255,250,225,0.95)',
        boxShadow: '0 0 16px rgba(240,185,50,0.95), 0 2px 6px rgba(90,50,10,0.35)',
        animation: 'pulse 1.2s ease-in-out infinite', pointerEvents: 'auto',
      }} />
  );
}

// A circle drawn UNDER a checker to mark that it moved. 'trail' = a piece moved
// this turn (persists until Ashton rolls); 'hover' = the piece a hovered die moved.
function UnderCircle({ x, y, cs, variant }) {
  const size = cs * 1.55;
  const isHover = variant === 'hover';
  return (
    <div style={{
      position: 'absolute', left: `${x}%`, top: `${y}%`,
      width: `${size}%`, paddingTop: `${size}%`,
      transform: 'translate(-50%,-50%)',
      borderRadius: '50%', pointerEvents: 'none',
      zIndex: isHover ? 11 : 3,
      border: isHover ? '3px solid rgba(240,200,80,0.95)' : '3px solid rgba(190,110,55,0.75)',
      background: isHover ? 'rgba(240,200,80,0.14)' : 'rgba(190,110,55,0.1)',
      boxShadow: isHover
        ? '0 0 18px rgba(240,200,80,0.75)'
        : '0 0 10px rgba(190,110,55,0.5)',
      animation: isHover ? 'none' : 'pulse 1.8s ease-in-out infinite',
    }} />
  );
}

function CalibDot({ x, y, label, color }) {
  return (
    <div style={{
      position: 'absolute', left: `${x}%`, top: `${y}%`,
      transform: 'translate(-50%,-50%)', zIndex: 30, pointerEvents: 'none',
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1,
    }}>
      <div style={{
        width: 14, height: 14, borderRadius: '50%', background: color,
        border: '2px solid white', boxShadow: '0 1px 4px rgba(0,0,0,0.5)', flexShrink: 0,
      }} />
      <span style={{
        fontSize: 9, fontFamily: 'monospace', fontWeight: 'bold', color: '#fff',
        background: 'rgba(0,0,0,0.65)', padding: '0 3px', borderRadius: 2, lineHeight: '13px',
      }}>
        {label}
      </span>
    </div>
  );
}

function BorneOffPile({ count, x, y, player, cs }) {
  return (
    <div style={{
      position: 'absolute', left: `${x}%`, top: `${y}%`,
      transform: 'translate(-50%,-50%)',
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2, zIndex: 4,
    }}>
      <div style={{
        width: `${cs * 0.5}vw`, height: `${cs * 0.5}vw`, borderRadius: '50%', flexShrink: 0,
        background: player === 'ashton' ? '#e8d9b8' : '#7a5430',
        border: '1px solid rgba(0,0,0,0.2)',
      }} />
      <span style={{ fontSize: 10, color: '#7a5430', fontFamily: 'Georgia, serif', lineHeight: 1 }}>
        ×{count}
      </span>
    </div>
  );
}
