import { useState, useRef } from 'react';
import { legalDestinations } from '../game/gameLogic.js';
import boards from '../game/boards/index.js';

// ─── Piece images (loaded at build time by Vite) ──────────────────────────────
// These files are generated by:  npm run extract-pieces
// If the directories don't exist yet, both arrays will be empty and checkers
// will fall back to solid-colour circles until you run the script and restart.
const _ashtonMods  = import.meta.glob('../assets/pieces/ashton/*.png',  { eager: true });
const _charlieMods = import.meta.glob('../assets/pieces/charlie/*.png', { eager: true });

// Sort by filename (piece-01, piece-02, …) for a consistent 0-based index
const ASHTON_PIECES  = Object.keys(_ashtonMods ).sort().map(k => _ashtonMods [k].default);
const CHARLIE_PIECES = Object.keys(_charlieMods).sort().map(k => _charlieMods[k].default);

const ALL_PIECES = { ashton: ASHTON_PIECES, charlie: CHARLIE_PIECES };

// ─── Calibration mode ────────────────────────────────────────────────────────
// Set to true, run dev server, tap points in order, read console, paste into
// sharpieBoard.js, then set back to false.
const CALIBRATION_MODE = false;

const CALIB_TARGETS = [
  ...Array.from({ length: 24 }, (_, i) => ({
    label: `Point ${i}`,
    fmt: (x, y) => `    ${String(i).padEnd(2)}: { x: ${x}, y: ${y} },`,
  })),
  { label: 'Bar — Ashton',       fmt: (x, y) => `  bar.ashton:   { x: ${x}, y: ${y} },` },
  { label: 'Bar — Charlie',      fmt: (x, y) => `  bar.charlie:  { x: ${x}, y: ${y} },` },
  { label: 'Bear-off — Ashton',  fmt: (x, y) => `  bearOff.ashton:  { x: ${x}, y: ${y} },` },
  { label: 'Bear-off — Charlie', fmt: (x, y) => `  bearOff.charlie: { x: ${x}, y: ${y} },` },
];

// ─── Image lookup ─────────────────────────────────────────────────────────────
// Maps (player, point/bar slot, stack index) → a piece image URL for this game.
// Uses a per-game shuffle stored in gameState.pieceImages so the arrangement
// looks handmade and is stable through the whole game session.
function getImg(player, slotId, stackIdx, pieceImages) {
  const pieces = ALL_PIECES[player];
  if (!pieces?.length || !pieceImages?.[player]) return null;
  // Hash slot + stack to an index in the shuffled array
  const n = ((slotId * 7 + stackIdx * 3) % 15 + 15) % 15;
  return pieces[pieceImages[player][n]] ?? null;
}

// ─── Position helpers — all coordinate math driven by board config ────────────

// After this many pieces stacked vertically, start a new side-by-side column.
const COL_CAPACITY = 5;

function checkerPos(config, pointIndex, stackIndex) {
  const base     = config.points[pointIndex];
  const isBottom = pointIndex <= 11;
  const dir      = isBottom ? config.stackDirection.bottom : config.stackDirection.top;

  const col = Math.floor(stackIndex / COL_CAPACITY); // 0 = first column, 1 = second, …
  const row = stackIndex % COL_CAPACITY;              // position within the column

  // Vertical: stack within the column, same as before
  const dy = dir === 'up' ? -row * config.stackStep : row * config.stackStep;

  // Horizontal: overflow columns spread outward from the bar toward the board edge.
  // Points with x < 50 are left of bar → second column shifts left; right → right.
  const xDir = base.x < 50 ? -1 : 1;
  const dx   = col * config.checkerSize * 0.95 * xDir;

  return { x: base.x + dx, y: base.y + dy };
}

function barPos(config, player, stackIndex) {
  const base   = config.bar[player];
  const dirKey = player === 'ashton' ? 'barAshton' : 'barCharlie';
  const dir    = config.stackDirection[dirKey];
  const dy     = dir === 'up' ? -stackIndex * config.stackStep : stackIndex * config.stackStep;
  return { x: base.x, y: base.y + dy };
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function BackgammonBoard({ state, onSelectPiece, onMovePiece, boardId = 'sharpie' }) {
  const config = boards[boardId] ?? boards['sharpie'];
  const boardRef = useRef(null);

  const [calibTarget, setCalibTarget] = useState(0);
  const [cursorPx, setCursorPx] = useState(null);

  const { points, bar, borneOff, selectedPoint, currentPlayer, phase, pieceImages } = state;

  const destinations = selectedPoint !== null && phase === 'moving' && currentPlayer === 'ashton'
    ? legalDestinations(state, selectedPoint)
    : [];

  // ── Calibration ───────────────────────────────────────────────────────────
  function handleCalibrationTap(e) {
    const rect = boardRef.current?.getBoundingClientRect();
    if (!rect) return;
    const x = ((e.clientX - rect.left) / rect.width  * 100).toFixed(1);
    const y = ((e.clientY - rect.top)  / rect.height * 100).toFixed(1);
    const target = CALIB_TARGETS[calibTarget];
    if (target) { console.log(target.fmt(x, y)); setCalibTarget(t => t + 1); }
  }

  // ── Game interactions ─────────────────────────────────────────────────────
  function handlePointTap(i) {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && destinations.includes(i)) onMovePiece(selectedPoint, i);
    else onSelectPiece(i);
  }
  function handleBarTap() {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && destinations.includes('off')) onMovePiece(selectedPoint, 'off');
    else onSelectPiece('bar');
  }
  function handleBearOffTap() {
    if (CALIBRATION_MODE || phase !== 'moving' || currentPlayer !== 'ashton') return;
    if (selectedPoint !== null && destinations.includes('off')) onMovePiece(selectedPoint, 'off');
  }

  const cs   = config.checkerSize;
  const done = calibTarget >= CALIB_TARGETS.length;

  return (
    <>
      {CALIBRATION_MODE && (
        <div style={{
          fontFamily: 'monospace', fontSize: 12, color: '#5a3010',
          background: 'rgba(255,240,200,0.95)', border: '1px solid #c8a050',
          borderRadius: 6, padding: '5px 10px', marginBottom: 6,
        }}>
          {done
            ? '✓ Done — paste console output into sharpieBoard.js'
            : <>CALIBRATION — tap <strong>{CALIB_TARGETS[calibTarget].label}</strong> &nbsp;({calibTarget + 1}/{CALIB_TARGETS.length})</>
          }
        </div>
      )}

      <div
        ref={boardRef}
        onPointerDown={CALIBRATION_MODE ? handleCalibrationTap : undefined}
        onPointerMove={CALIBRATION_MODE ? (e) => {
          const r = boardRef.current?.getBoundingClientRect();
          if (r) setCursorPx({ x: e.clientX - r.left, y: e.clientY - r.top });
        } : undefined}
        onPointerLeave={CALIBRATION_MODE ? () => setCursorPx(null) : undefined}
        style={{
          position: 'relative', width: '100%',
          touchAction: 'manipulation', userSelect: 'none',
          WebkitTapHighlightColor: 'transparent',
          cursor: CALIBRATION_MODE ? 'crosshair' : 'default',
        }}
      >
        <img src={config.image} alt="backgammon board" draggable={false}
          style={{ width: '100%', display: 'block', borderRadius: 12 }} />

        {/* Calibration: existing-position markers */}
        {CALIBRATION_MODE && Object.entries(config.points).map(([i, pos]) => (
          <CalibDot key={`cd-${i}`} x={pos.x} y={pos.y} label={i} color="#2080ff" />
        ))}
        {CALIBRATION_MODE && <>
          <CalibDot x={config.bar.ashton.x}  y={config.bar.ashton.y}  label="BA" color="#e05000" />
          <CalibDot x={config.bar.charlie.x} y={config.bar.charlie.y} label="BC" color="#e05000" />
          <CalibDot x={config.bearOff.ashton.x}  y={config.bearOff.ashton.y}  label="OA" color="#008040" />
          <CalibDot x={config.bearOff.charlie.x} y={config.bearOff.charlie.y} label="OC" color="#008040" />
        </>}

        {/* Calibration: cursor label */}
        {CALIBRATION_MODE && cursorPx && !done && (
          <div style={{
            position: 'absolute', left: cursorPx.x + 16, top: cursorPx.y + 4,
            pointerEvents: 'none', zIndex: 50, background: 'rgba(0,0,0,0.75)',
            color: '#fff', fontFamily: 'monospace', fontSize: 11,
            padding: '2px 7px', borderRadius: 4, whiteSpace: 'nowrap',
          }}>
            → {CALIB_TARGETS[calibTarget]?.label}
          </div>
        )}

        {/* Bear-off tap zone */}
        {!CALIBRATION_MODE && destinations.includes('off') && (<>
          <div onPointerDown={(e) => { e.stopPropagation(); handleBearOffTap(); }}
            style={{
              position: 'absolute',
              left: `${config.bearOff.ashton.x - cs}%`, top: `${config.bearOff.ashton.y - cs * 2}%`,
              width: `${cs * 2}%`, height: `${cs * 4}%`, zIndex: 20, cursor: 'pointer',
            }} />
          <DestDot x={config.bearOff.ashton.x} y={config.bearOff.ashton.y} cs={cs} onTap={handleBearOffTap} />
        </>)}

        {/* Bar tap zone */}
        {!CALIBRATION_MODE && (
          <div onPointerDown={(e) => { e.stopPropagation(); handleBarTap(); }}
            style={{
              position: 'absolute',
              left: `${config.bar.ashton.x - 6}%`, top: '5%', width: '12%', height: '90%',
              zIndex: 10,
              cursor: bar.ashton > 0 || selectedPoint === 'bar' ? 'pointer' : 'default',
            }} />
        )}

        {/* Destination dots */}
        {!CALIBRATION_MODE && destinations.map(dest => {
          if (dest === 'off') return null;
          const pos = checkerPos(config, dest, points[dest].count);
          return <DestDot key={`dest-${dest}`} x={pos.x} y={pos.y} cs={cs} onTap={() => handlePointTap(dest)} />;
        })}

        {/* Checkers on points */}
        {points.map((pt, i) => {
          if (!pt.count || !pt.player) return null;
          const isOverflow = pt.count > COL_CAPACITY;
          return Array.from({ length: pt.count }).map((_, si) => {
            const pos = checkerPos(config, i, si);
            const img = getImg(pt.player, i, si, pieceImages);
            // Top of any column is interactive so clicks register even on the 2nd column
            const colTop = (si + 1) % COL_CAPACITY === 0 || si === pt.count - 1;
            return (
              <Checker key={`pt-${i}-${si}`} x={pos.x} y={pos.y} cs={cs} player={pt.player} img={img}
                selected={selectedPoint === i && si === pt.count - 1}
                isTopmost={colTop}
                onTap={() => handlePointTap(i)}
                interactive={!CALIBRATION_MODE && phase === 'moving' && currentPlayer === 'ashton' && pt.player === 'ashton'}
              />
            );
          });
        })}

        {/* Overflow count badge — shown only when a point has more than COL_CAPACITY pieces */}
        {!CALIBRATION_MODE && points.map((pt, i) => {
          if (!pt.count || pt.count <= COL_CAPACITY) return null;
          const base     = config.points[i];
          const isBottom = i <= 11;
          // Place the badge just beyond the outermost checker (near the triangle tip)
          const badgeY = isBottom ? base.y + 5 : base.y - 5;
          return (
            <div key={`badge-${i}`} style={{
              position: 'absolute',
              left:   `${base.x}%`,
              top:    `${badgeY}%`,
              transform: 'translate(-50%, -50%)',
              zIndex: 20, pointerEvents: 'none',
              width: 16, height: 16, borderRadius: '50%',
              background: 'rgba(60,35,10,0.82)',
              color: '#f5e8c0',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 9, fontFamily: 'Georgia, serif', fontWeight: 'bold',
              boxShadow: '0 1px 4px rgba(0,0,0,0.4)',
              lineHeight: 1,
            }}>
              {pt.count}
            </div>
          );
        })}

        {/* Bar — Ashton */}
        {Array.from({ length: bar.ashton }).map((_, i) => {
          const pos = barPos(config, 'ashton', i);
          const img = getImg('ashton', 24, i, pieceImages);
          return (
            <Checker key={`bar-a-${i}`} x={pos.x} y={pos.y} cs={cs} player="ashton" img={img}
              selected={selectedPoint === 'bar' && i === bar.ashton - 1}
              isTopmost={i === bar.ashton - 1}
              onTap={handleBarTap}
              interactive={!CALIBRATION_MODE && phase === 'moving' && currentPlayer === 'ashton'}
            />
          );
        })}

        {/* Bar — Charlie */}
        {Array.from({ length: bar.charlie }).map((_, i) => {
          const pos = barPos(config, 'charlie', i);
          const img = getImg('charlie', 25, i, pieceImages);
          return (
            <Checker key={`bar-c-${i}`} x={pos.x} y={pos.y} cs={cs} player="charlie" img={img}
              selected={false} isTopmost={false} onTap={() => {}} interactive={false}
            />
          );
        })}

        {/* Borne-off counters */}
        {borneOff.ashton  > 0 && <BorneOffPile count={borneOff.ashton}  x={config.bearOff.ashton.x}  y={config.bearOff.ashton.y}  player="ashton"  cs={cs} />}
        {borneOff.charlie > 0 && <BorneOffPile count={borneOff.charlie} x={config.bearOff.charlie.x} y={config.bearOff.charlie.y} player="charlie" cs={cs} />}

        {/* Point tap targets (triangle areas) */}
        {!CALIBRATION_MODE && Array.from({ length: 24 }).map((_, i) => {
          const base     = config.points[i];
          const isBottom = i <= 11;
          return (
            <div key={`tap-${i}`}
              onPointerDown={(e) => { e.stopPropagation(); handlePointTap(i); }}
              style={{
                position: 'absolute',
                left: `${base.x - cs / 2}%`,
                top:  isBottom ? '52%' : `${base.y}%`,
                width: `${cs}%`, height: '42%',
                transform: isBottom ? 'none' : 'translateY(-100%)',
                zIndex: 8, cursor: 'pointer',
              }} />
          );
        })}
      </div>
    </>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function Checker({ x, y, cs, player, img, selected, isTopmost, onTap, interactive }) {
  return (
    <div
      onPointerDown={interactive && isTopmost ? (e) => { e.stopPropagation(); onTap(); } : undefined}
      style={{
        position: 'absolute', left: `${x}%`, top: `${y}%`,
        width: `${cs}%`, paddingTop: `${cs}%`,
        transform: `translate(-50%,-50%)${selected ? ' translateY(-6px) scale(1.08)' : ''}`,
        transition: 'transform 0.15s ease',
        zIndex: selected ? 12 : isTopmost ? 6 : 5,
        cursor: interactive && isTopmost ? 'pointer' : 'default',
        pointerEvents: isTopmost ? 'auto' : 'none',
      }}
    >
      {img ? (
        <img src={img} draggable={false} style={{
          position: 'absolute', inset: 0, width: '100%', height: '100%',
          borderRadius: '50%',
          boxShadow: selected
            ? '0 0 0 3px #f0c040, 0 4px 16px rgba(240,192,64,0.6)'
            : '0 1px 4px rgba(0,0,0,0.25)',
        }} />
      ) : (
        <div style={{
          position: 'absolute', inset: 0, borderRadius: '50%',
          background: player === 'ashton' ? '#e8d9b8' : '#7a5430',
          border: selected ? '3px solid #f0c040' : '2px solid rgba(0,0,0,0.2)',
          boxShadow: selected
            ? '0 0 0 3px #f0c040, 0 4px 16px rgba(240,192,64,0.6)'
            : '0 1px 4px rgba(0,0,0,0.25)',
        }} />
      )}
    </div>
  );
}

function DestDot({ x, y, cs, onTap }) {
  const d = cs * 0.6;
  return (
    <div onPointerDown={(e) => { e.stopPropagation(); onTap(); }}
      style={{
        position: 'absolute', left: `${x}%`, top: `${y}%`,
        width: `${d}%`, paddingTop: `${d}%`,
        transform: 'translate(-50%,-50%)', zIndex: 14, cursor: 'pointer',
        borderRadius: '50%', background: 'rgba(230,180,60,0.65)',
        boxShadow: '0 0 14px rgba(230,180,60,0.8)',
        animation: 'pulse 1.2s ease-in-out infinite', pointerEvents: 'auto',
      }} />
  );
}

function CalibDot({ x, y, label, color }) {
  return (
    <div style={{
      position: 'absolute', left: `${x}%`, top: `${y}%`,
      transform: 'translate(-50%,-50%)', zIndex: 30, pointerEvents: 'none',
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1,
    }}>
      <div style={{
        width: 14, height: 14, borderRadius: '50%', background: color,
        border: '2px solid white', boxShadow: '0 1px 4px rgba(0,0,0,0.5)', flexShrink: 0,
      }} />
      <span style={{
        fontSize: 9, fontFamily: 'monospace', fontWeight: 'bold', color: '#fff',
        background: 'rgba(0,0,0,0.65)', padding: '0 3px', borderRadius: 2, lineHeight: '13px',
      }}>
        {label}
      </span>
    </div>
  );
}

function BorneOffPile({ count, x, y, player, cs }) {
  return (
    <div style={{
      position: 'absolute', left: `${x}%`, top: `${y}%`,
      transform: 'translate(-50%,-50%)',
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2, zIndex: 4,
    }}>
      <div style={{
        width: `${cs * 0.5}vw`, height: `${cs * 0.5}vw`, borderRadius: '50%', flexShrink: 0,
        background: player === 'ashton' ? '#e8d9b8' : '#7a5430',
        border: '1px solid rgba(0,0,0,0.2)',
      }} />
      <span style={{ fontSize: 10, color: '#7a5430', fontFamily: 'Georgia, serif', lineHeight: 1 }}>
        ×{count}
      </span>
    </div>
  );
}
